[ci skip] don't fail if nothing to build - just proceed with quick skip stages
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

diff --git a/build/ci/sync-midstream-sync-downstream-build-downstream.yml b/build/ci/sync-midstream-sync-downstream-build-downstream.yml
--- a/build/ci/sync-midstream-sync-downstream-build-downstream.yml
+++ b/build/ci/sync-midstream-sync-downstream-build-downstream.yml
@@ -27,7 +27,8 @@ sync-midstream:
       elif [[ -f /tmp/sync-midstream.sh.result.txt ]]; then
         mkdir -p "${CI_PROJECT_DIR}/"outputs1; touch "${CI_PROJECT_DIR}/"outputs1/sync-midstream.sh.result.txt
         mv /tmp/sync-midstream.sh.result.txt "${CI_PROJECT_DIR}/"outputs1/sync-midstream.sh.result.txt
-        exit 71
+        # don't fail the build with a >0 exit code - it's OK if nothing happened
+        # exit 71
       fi
   # keep artifacts for 8 hrs so we can use them for multiple scheduled quay/helm chart updates
   artifacts:
@@ -123,7 +124,8 @@ build-downstream:
       [SKIP] Nothing to build downstream - no changes in midstream sync/ folder, or no such file sync-midstream.sh.diff.txt !
       ===================================
       " | tee -a outputs3/build-downstream.sh.NONE_BUILT.result.txt
-        exit 73
+        # don't fail the build with a >0 exit code - it's OK if nothing happened
+        # exit 73
       else
         echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -1; echo
         ./build/ci/build-containers.sh
