disable downstream sync and builds - let Konflux handle itself
Signed-off-by: Nick Boldt <nboldt@redhat.com>

diff --git a/build/ci/sync-midstream-sync-downstream-build-downstream.yml b/build/ci/sync-midstream-sync-downstream-build-downstream.yml
--- a/build/ci/sync-midstream-sync-downstream-build-downstream.yml
+++ b/build/ci/sync-midstream-sync-downstream-build-downstream.yml
@@ -17,7 +17,8 @@ sync-midstream:
       # sync, build and commit changes
       echo "Running sync-midstream.sh for $GITLAB_USER_LOGIN in branch $CI_COMMIT_REF_NAME ..."
       # can add --force flag here to push with -f
-      ./build/ci/sync-midstream.sh -b "$CI_COMMIT_REF_NAME" --gitlab-pipeline-push || exit 15
+      # RHIDP-3698 local yarn build disabled as we are letting Konflux handle that now (--no-build)
+      ./build/ci/sync-midstream.sh -b "$CI_COMMIT_REF_NAME" --gitlab-pipeline-push --no-build || exit 15
       echo "Committed: $CI_COMMIT_REF_NAME"
       set -x
       echo "Currently in $(pwd)"
@@ -35,110 +36,112 @@ sync-midstream:
     expire_in: 8 hours
     paths: [outputs1/]
 
-
-# if there's a change that we need to build
-sync-downstream:
-  extends: .shared_config
-  stage: sync-downstream
-  needs: ["sync-midstream"]
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /rhdh-[0-9.]+-rhel-9/
-    # for scheduled runs, check env var
-    - if: $CI_PIPELINE_SOURCE == "schedule" && $DO_SYNC_DOWNSTREAM != "False"
-  parallel:
-    matrix:
-      - REPO: 
-        - rhdh-hub
-        - rhdh-operator
-        - rhdh-operator-bundle
-  script:
-    - |
-      dnf -y -q install git
-      # if sync/sync/upstream_SHA_$REPO updated in the last two commits (because each midstream sync is two commits), then sync to downstream
-      git pull origin || true
-      sync_check="$(git diff --name-only HEAD~2 sync/upstream_SHA_$REPO || true)"
-      sync_check2="$(cat "${CI_PROJECT_DIR}/"outputs1/sync-midstream.sh.diff.txt)"
-      echo "
-      =================================
-      sync check:
-      $sync_check
-      ---
-      $sync_check2
-      ================================="
-
-      # to force the sync if it fails to push changes
-      if [[ $DO_SYNC_DOWNSTREAM == "Force" ]]; then
-        echo "##### FORCING DOWNSTREAM SYNC via gitlab pipeline parameter DO_SYNC_DOWNSTREAM == Force #####"
-        sync_check="DO_SYNC_DOWNSTREAM = $DO_SYNC_DOWNSTREAM"
-      fi
-
-      if [[ $sync_check == "" ]] && [[ $sync_check2 == "" ]]; then
-        mkdir -p outputs2; touch outputs2/sync-downstream.sh.result.txt
-        echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -4; echo
-        echo " 
-      ==============================================================
-      [SKIP] Nothing to sync to downstream: midstream diff is empty!
-      ==============================================================
-      " | tee outputs2/sync-downstream.sh.result.txt
-        # exit 72
-      else
-        echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -1; echo
-        echo "Sync to downstream in branch $CI_COMMIT_REF_NAME ..."
-        ./build/ci/sync-downstream.sh -b "$CI_COMMIT_REF_NAME" -d $REPO || exit 16
-        echo "Currently in $(pwd)"
-        # store diff to be used in next stage
-        if [[ $(cat /tmp/sync-downstream.sh.$REPO.diff.txt | wc -l) -gt 0 ]]; then
-          mkdir -p outputs2; touch outputs2/sync-downstream.sh.$REPO.diff.txt
-          mv /tmp/sync-downstream.sh.$REPO.diff.txt outputs2/sync-downstream.sh.$REPO.diff.txt
-        else
-          mkdir -p outputs2; touch outputs2/sync-downstream.sh.result.txt
-          # do not use "Nothing to" here so that these don't count as stage skip messages in the 'review-stages' stage
-            echo " 
-          ==============================================================
-          [INFO] No change to $REPO in midstream or downstream!
-          ==============================================================
-          " | tee -a outputs2/sync-downstream.sh.result.txt
-        fi
-      fi
-  artifacts:
-    expire_in: 8 hours
-    paths: [outputs2/]
-
-# run builds in series, not parallel
-build-downstream:
-  extends: .shared_config
-  stage: build-downstream
-  needs: ["sync-downstream"]
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /rhdh-[0-9.]+-rhel-9/
-    # for scheduled runs, check env var
-    - if: $CI_PIPELINE_SOURCE == "schedule" && $DO_BUILD_DOWNSTREAM == "True"
-  timeout: 8 hours
-  script:
-    - |
-      dnf -y -q install git
-      # if sync/ folder updated, then build downstream
-      sync_check="$(git diff --name-only HEAD~1 sync/ || true; git diff --name-only HEAD~2 sync/ || true)"
-      echo "
-      =================================
-      sync check:
-      $sync_check
-      ================================="
-      if [[ $sync_check == "" ]] && [[ ! -f outputs1/sync-midstream.sh.diff.txt ]]; then
-        mkdir -p outputs3; touch outputs3/build-downstream.sh.NONE_BUILT.result.txt
-        echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -4; echo
-        echo " 
-      ===================================
-      [SKIP] Nothing to build downstream - no changes in midstream sync/ folder, or no such file sync-midstream.sh.diff.txt !
-      ===================================
-      " | tee -a outputs3/build-downstream.sh.NONE_BUILT.result.txt
-        ./build/ci/cancel-pipeline.sh
-        # don't fail the build with a >0 exit code - it's OK if nothing happened
-        # exit 73
-      else
-        echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -1; echo
-        ./build/ci/build-containers.sh
-      fi
-  artifacts:
-    expire_in: 8 hours
-    paths: [outputs3/]
+# RHIDP-3698 OSBS builds disabled as we are letting Konflux handle them - https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/rhdh/applications/rhdh-1
+# # if there's a change that we need to build
+# sync-downstream:
+#   extends: .shared_config
+#   stage: sync-downstream
+#   needs: ["sync-midstream"]
+#   rules:
+#     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /rhdh-[0-9.]+-rhel-9/
+#     # for scheduled runs, check env var
+#     - if: $CI_PIPELINE_SOURCE == "schedule" && $DO_SYNC_DOWNSTREAM != "False"
+#   parallel:
+#     matrix:
+#       - REPO: 
+#         - rhdh-hub
+#         - rhdh-operator
+#         - rhdh-operator-bundle
+#   script:
+#     - |
+#       dnf -y -q install git
+#       # if sync/sync/upstream_SHA_$REPO updated in the last two commits (because each midstream sync is two commits), then sync to downstream
+#       git pull origin || true
+#       sync_check="$(git diff --name-only HEAD~2 sync/upstream_SHA_$REPO || true)"
+#       sync_check2="$(cat "${CI_PROJECT_DIR}/"outputs1/sync-midstream.sh.diff.txt)"
+#       echo "
+#       =================================
+#       sync check:
+#       $sync_check
+#       ---
+#       $sync_check2
+#       ================================="
+#
+#       # to force the sync if it fails to push changes
+#       if [[ $DO_SYNC_DOWNSTREAM == "Force" ]]; then
+#         echo "##### FORCING DOWNSTREAM SYNC via gitlab pipeline parameter DO_SYNC_DOWNSTREAM == Force #####"
+#         sync_check="DO_SYNC_DOWNSTREAM = $DO_SYNC_DOWNSTREAM"
+#       fi
+#
+#       if [[ $sync_check == "" ]] && [[ $sync_check2 == "" ]]; then
+#         mkdir -p outputs2; touch outputs2/sync-downstream.sh.result.txt
+#         echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -4; echo
+#         echo " 
+#       ==============================================================
+#       [SKIP] Nothing to sync to downstream: midstream diff is empty!
+#       ==============================================================
+#       " | tee outputs2/sync-downstream.sh.result.txt
+#         # exit 72
+#       else
+#         echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -1; echo
+#         echo "Sync to downstream in branch $CI_COMMIT_REF_NAME ..."
+#         ./build/ci/sync-downstream.sh -b "$CI_COMMIT_REF_NAME" -d $REPO || exit 16
+#         echo "Currently in $(pwd)"
+#         # store diff to be used in next stage
+#         if [[ $(cat /tmp/sync-downstream.sh.$REPO.diff.txt | wc -l) -gt 0 ]]; then
+#           mkdir -p outputs2; touch outputs2/sync-downstream.sh.$REPO.diff.txt
+#           mv /tmp/sync-downstream.sh.$REPO.diff.txt outputs2/sync-downstream.sh.$REPO.diff.txt
+#         else
+#           mkdir -p outputs2; touch outputs2/sync-downstream.sh.result.txt
+#           # do not use "Nothing to" here so that these don't count as stage skip messages in the 'review-stages' stage
+#             echo " 
+#           ==============================================================
+#           [INFO] No change to $REPO in midstream or downstream!
+#           ==============================================================
+#           " | tee -a outputs2/sync-downstream.sh.result.txt
+#         fi
+#       fi
+#   artifacts:
+#     expire_in: 8 hours
+#     paths: [outputs2/]
+#
+# RHIDP-3698 OSBS builds disabled as we are letting Konflux handle them - https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/rhdh/applications/rhdh-1
+# TODO https://issues.redhat.com/browse/RHIDP-4014 hermetic builds with Cachi2
+# # run builds in series, not parallel
+# build-downstream:
+#   extends: .shared_config
+#   stage: build-downstream
+#   needs: ["sync-downstream"]
+#   rules:
+#     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /rhdh-[0-9.]+-rhel-9/
+#     # for scheduled runs, check env var
+#     - if: $CI_PIPELINE_SOURCE == "schedule" && $DO_BUILD_DOWNSTREAM == "True"
+#   timeout: 8 hours
+#   script:
+#     - |
+#       dnf -y -q install git
+#       # if sync/ folder updated, then build downstream
+#       sync_check="$(git diff --name-only HEAD~1 sync/ || true; git diff --name-only HEAD~2 sync/ || true)"
+#       echo "
+#       =================================
+#       sync check:
+#       $sync_check
+#       ================================="
+#       if [[ $sync_check == "" ]] && [[ ! -f outputs1/sync-midstream.sh.diff.txt ]]; then
+#         mkdir -p outputs3; touch outputs3/build-downstream.sh.NONE_BUILT.result.txt
+#         echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -4; echo
+#         echo " 
+#       ===================================
+#       [SKIP] Nothing to build downstream - no changes in midstream sync/ folder, or no such file sync-midstream.sh.diff.txt !
+#       ===================================
+#       " | tee -a outputs3/build-downstream.sh.NONE_BUILT.result.txt
+#         ./build/ci/cancel-pipeline.sh
+#         # don't fail the build with a >0 exit code - it's OK if nothing happened
+#         # exit 73
+#       else
+#         echo; git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset :: %s @ %cN <%cE> (%cD - %cr)' --name-only -1; echo
+#         ./build/ci/build-containers.sh
+#       fi
+#   artifacts:
+#     expire_in: 8 hours
+#     paths: [outputs3/]
